language: java

before_script:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

cache:
  directories:
  - $HOME/.m2

jobs:
  include:
  - stage: ☕ jdk.java.net - Java Development Kit builds, from Oracle
    env: JDK=ea
    script: source ./install-jdk.sh --verbose --feature ea
  - stage: JDK 14
    env: JDK=14
    script: source ./install-jdk.sh --feature 14