language: java

before_script:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
  - stage: ☕ jdk.java.net - Java Development Kit builds, from Oracle
    env: JDK=ea
    script: source ./install-jdk.sh --verbose --feature ea
  - stage: JDK 14
    env: JDK=14
    script: source ./install-jdk.sh --feature 14

after_script:
- echo JAVA_HOME = ${JAVA_HOME}
- echo PATH = ${PATH}
- ls ${JAVA_HOME}
- java -version
